# https://kserve.github.io/website/modelserving/storage/s3/s3/
apiVersion: v1
kind: Secret
metadata:
  name: s3creds
  annotations:
     serving.kserve.io/s3-endpoint: 192.168.134.20:31064 # replace with your s3 endpoint e.g minio-service.kubeflow:9000, http:// 는 빼야 함, TODO 9000 포트가 열리면 9000 으로 변경해야 함
     serving.kserve.io/s3-usehttps: "0" # by default 1, if testing with minio you can set to 0
    #  serving.kserve.io/s3-region: "ap-northeast-2"
     serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
